#+PROPERTY: header-args :results silent

* Emacs primitives
** Package management

#+BEGIN_SRC emacs-lisp
(require 'package)
(setq package-archives
	  '(("gnu-elpa" . "https://elpa.gnu.org/packages/")
		("nongnu-elpa" . "https://elpa.nongnu.org/nongnu/")
		("melpa" . "https://melpa.org/packages/")))
#+END_SRC

*** Use-package
Bootstrapping use-package.

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
#+END_SRC

** Save behaviour

Stop polluting the folders with annoyings =*~= backups.
#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
#+END_SRC

** Suppress endless warnings

Emacs spams =‘:events-buffer-scrollback-size’ deprecated. Use ‘events-buffer-config’.= everytime a file is open.

#+begin_src emacs-lisp
 (setq warning-minimum-level :error)
#+end_src

** Autocompletion

Attempt to disable annoying systematic autocompletion (does not seem to work).

#+begin_src emacs-lisp
(setq tab-always-indent t)
#+end_src


* Interface

** Undo tree

#+BEGIN_SRC emacs-lisp
(use-package undo-tree
  :ensure t)
(global-undo-tree-mode 1)
;; make ctrl-z undo
(global-set-key (kbd "C-z") 'undo)
;; make ctrl-Z redo
(defalias 'redo 'undo-tree-redo)
(global-set-key (kbd "C-S-z") 'redo)
;; also using C-M-Z for console
(global-set-key (kbd "C-M-z") 'redo)
#+END_SRC

Stop generating invading =.~undo-tree~= files:
#+begin_src emacs-lisp
(setq undo-tree-auto-save-history nil)
#+end_src

** Font

#+begin_src emacs-lisp
  (set-face-attribute 'default nil
                      :family "Jetbrains Mono"
                      :height 100
                      :weight 'normal
                      :width 'normal)
#+end_src

** Change window on french keyboard

Cycles through windows.
The lambda seems necessary because =ace-window= seems to highjack =other-window=.
#+begin_src emacs-lisp
(global-set-key (kbd "M-ù") (lambda ()(interactive) (other-window 1)))
#+end_src
(other-window)

** Shortcuts

#+begin_src emacs-lisp
(global-set-key (kbd "<f3>") 'revert-buffer)
#+end_src


* Org
** Remove unreadeable prettyfiers

#+begin_src emacs-lisp
(setq org-hide-emphasis-markers nil)
#+end_src

#+begin_src emacs-lisp
(setq org-modern-table nil)
#+end_src

** Scratch

Put the scratch buffer in org-mode by default.

#+begin_src emacs-lisp
(setq initial-major-mode 'org-mode)
(setq initial-scratch-message "#+property: header-args :results output
# This buffer is for text that is not saved, and for volatile org-mode snippets.
# To create a file, visit it with C-x C-f and enter text in its buffer.
")
#+end_src

** Disable code block indentation

#+begin_src emacs-lisp
(setq org-edit-src-content-indentation 0)
#+end_src
